/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyPejulRouteImport } from './routes/why-pejul'
import { Route as VentureBuildingRouteImport } from './routes/venture-building'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TeamRouteImport } from './routes/team'
import { Route as StrategySessionRouteImport } from './routes/strategy-session'
import { Route as StartupGrowthRouteImport } from './routes/startup-growth'
import { Route as SoftwareDevelopmentRouteImport } from './routes/software-development'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BusinessDigitizationRouteImport } from './routes/business-digitization'
import { Route as AiSolutionsRouteImport } from './routes/ai-solutions'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as PortfolioIdRouteImport } from './routes/portfolio.$id'

const WhyPejulRoute = WhyPejulRouteImport.update({
  id: '/why-pejul',
  path: '/why-pejul',
  getParentRoute: () => rootRouteImport,
} as any)
const VentureBuildingRoute = VentureBuildingRouteImport.update({
  id: '/venture-building',
  path: '/venture-building',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategySessionRoute = StrategySessionRouteImport.update({
  id: '/strategy-session',
  path: '/strategy-session',
  getParentRoute: () => rootRouteImport,
} as any)
const StartupGrowthRoute = StartupGrowthRouteImport.update({
  id: '/startup-growth',
  path: '/startup-growth',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareDevelopmentRoute = SoftwareDevelopmentRouteImport.update({
  id: '/software-development',
  path: '/software-development',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessDigitizationRoute = BusinessDigitizationRouteImport.update({
  id: '/business-digitization',
  path: '/business-digitization',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSolutionsRoute = AiSolutionsRouteImport.update({
  id: '/ai-solutions',
  path: '/ai-solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIdRoute = PortfolioIdRouteImport.update({
  id: '/portfolio/$id',
  path: '/portfolio/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-solutions': typeof AiSolutionsRoute
  '/business-digitization': typeof BusinessDigitizationRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/privacy': typeof PrivacyRoute
  '/software-development': typeof SoftwareDevelopmentRoute
  '/startup-growth': typeof StartupGrowthRoute
  '/strategy-session': typeof StrategySessionRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/venture-building': typeof VentureBuildingRoute
  '/why-pejul': typeof WhyPejulRoute
  '/portfolio/$id': typeof PortfolioIdRoute
  '/portfolio/': typeof PortfolioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-solutions': typeof AiSolutionsRoute
  '/business-digitization': typeof BusinessDigitizationRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/privacy': typeof PrivacyRoute
  '/software-development': typeof SoftwareDevelopmentRoute
  '/startup-growth': typeof StartupGrowthRoute
  '/strategy-session': typeof StrategySessionRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/venture-building': typeof VentureBuildingRoute
  '/why-pejul': typeof WhyPejulRoute
  '/portfolio/$id': typeof PortfolioIdRoute
  '/portfolio': typeof PortfolioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-solutions': typeof AiSolutionsRoute
  '/business-digitization': typeof BusinessDigitizationRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/privacy': typeof PrivacyRoute
  '/software-development': typeof SoftwareDevelopmentRoute
  '/startup-growth': typeof StartupGrowthRoute
  '/strategy-session': typeof StrategySessionRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/venture-building': typeof VentureBuildingRoute
  '/why-pejul': typeof WhyPejulRoute
  '/portfolio/$id': typeof PortfolioIdRoute
  '/portfolio/': typeof PortfolioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-solutions'
    | '/business-digitization'
    | '/contact'
    | '/industries'
    | '/privacy'
    | '/software-development'
    | '/startup-growth'
    | '/strategy-session'
    | '/team'
    | '/terms'
    | '/venture-building'
    | '/why-pejul'
    | '/portfolio/$id'
    | '/portfolio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-solutions'
    | '/business-digitization'
    | '/contact'
    | '/industries'
    | '/privacy'
    | '/software-development'
    | '/startup-growth'
    | '/strategy-session'
    | '/team'
    | '/terms'
    | '/venture-building'
    | '/why-pejul'
    | '/portfolio/$id'
    | '/portfolio'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-solutions'
    | '/business-digitization'
    | '/contact'
    | '/industries'
    | '/privacy'
    | '/software-development'
    | '/startup-growth'
    | '/strategy-session'
    | '/team'
    | '/terms'
    | '/venture-building'
    | '/why-pejul'
    | '/portfolio/$id'
    | '/portfolio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiSolutionsRoute: typeof AiSolutionsRoute
  BusinessDigitizationRoute: typeof BusinessDigitizationRoute
  ContactRoute: typeof ContactRoute
  IndustriesRoute: typeof IndustriesRoute
  PrivacyRoute: typeof PrivacyRoute
  SoftwareDevelopmentRoute: typeof SoftwareDevelopmentRoute
  StartupGrowthRoute: typeof StartupGrowthRoute
  StrategySessionRoute: typeof StrategySessionRoute
  TeamRoute: typeof TeamRoute
  TermsRoute: typeof TermsRoute
  VentureBuildingRoute: typeof VentureBuildingRoute
  WhyPejulRoute: typeof WhyPejulRoute
  PortfolioIdRoute: typeof PortfolioIdRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-pejul': {
      id: '/why-pejul'
      path: '/why-pejul'
      fullPath: '/why-pejul'
      preLoaderRoute: typeof WhyPejulRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venture-building': {
      id: '/venture-building'
      path: '/venture-building'
      fullPath: '/venture-building'
      preLoaderRoute: typeof VentureBuildingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy-session': {
      id: '/strategy-session'
      path: '/strategy-session'
      fullPath: '/strategy-session'
      preLoaderRoute: typeof StrategySessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/startup-growth': {
      id: '/startup-growth'
      path: '/startup-growth'
      fullPath: '/startup-growth'
      preLoaderRoute: typeof StartupGrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software-development': {
      id: '/software-development'
      path: '/software-development'
      fullPath: '/software-development'
      preLoaderRoute: typeof SoftwareDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-digitization': {
      id: '/business-digitization'
      path: '/business-digitization'
      fullPath: '/business-digitization'
      preLoaderRoute: typeof BusinessDigitizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-solutions': {
      id: '/ai-solutions'
      path: '/ai-solutions'
      fullPath: '/ai-solutions'
      preLoaderRoute: typeof AiSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$id': {
      id: '/portfolio/$id'
      path: '/portfolio/$id'
      fullPath: '/portfolio/$id'
      preLoaderRoute: typeof PortfolioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiSolutionsRoute: AiSolutionsRoute,
  BusinessDigitizationRoute: BusinessDigitizationRoute,
  ContactRoute: ContactRoute,
  IndustriesRoute: IndustriesRoute,
  PrivacyRoute: PrivacyRoute,
  SoftwareDevelopmentRoute: SoftwareDevelopmentRoute,
  StartupGrowthRoute: StartupGrowthRoute,
  StrategySessionRoute: StrategySessionRoute,
  TeamRoute: TeamRoute,
  TermsRoute: TermsRoute,
  VentureBuildingRoute: VentureBuildingRoute,
  WhyPejulRoute: WhyPejulRoute,
  PortfolioIdRoute: PortfolioIdRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
